### ISSUE TITLE
Bug: log level filter level doesn't reset when loading another file using drag and drop

### ISSUE THREAD

**Issue by Henry8192** [y-scope/yscope-log-viewer#133]
### Bug

Log level filter should reset the filter level when loading another file. However, on drag and drop a new file, the log level filter doesn't reset (and new logs are not filtered).

### yscope-log-viewer version

82e677e

### Environment

Chrome: 131.0.6778.86

### Reproduction steps

1. Open a new log file with log viewer. 
2. Set log level filter.
3. Drag and drop another file, observe that the log level filter doesn't reset.

**Comment by junhaoliao** [comment]
@davemarco / @jackluo923 shall we persist the log level filter across different files?

**Comment by kirkrodrigues** [comment]
> should either be fixed

It needs to be fixed regardless since the logs are not filtered when the new file is loaded (even though the filter says it's enabled).

I would prefer we reset the filter when loading a new file.
