### ISSUE TITLE
Add a download button to the log browser

### ISSUE THREAD

**Issue by onerandomdude** [y-scope/yscope-log-viewer#4]
### Request

sometimes, users may want to download the log file to local, and perform actions on the log file locally, so it would be great if the log browser can have the functionality to be able to "download" it.

### Possible implementation

<img width="1625" alt="Screenshot 2023-02-28 at 11 12 38 PM" src="https://user-images.githubusercontent.com/48631960/222069387-a14ded3b-1718-4c4a-a091-8e567712c59b.png">

perhaps include a "download" button after "open file" button

**Comment by vishalpalaniappan** [comment]
Hi onerandomdude, 

Thanks for the feature request, we will be adding a download button for the compressed version of the log over the next day or two. These logs can be viewed in the viewer using drag and drop or the file input dialog. Once we start decoding logs to indexdDB, we will implement a solution to download uncompressed log files.
