### ISSUE TITLE
new-log-viewer: Load errors don't clear the data of the currently loaded file but the file no longer exists in the worker.

### ISSUE THREAD

**Issue by kirkrodrigues** [y-scope/yscope-log-viewer#75]
### Bug

After loading a file successfully, trying to load an invalid file (by dragging and dropping) will:

* clear the previously loaded file from the worker.
* cause an error to be logged.

This has two issues:

* Clearing the previously loaded file from the worker is undesirable.
* It doesn't clear the loaded file from the UI which means any actions (like page switching) will fail with console errors.

Ideally, we should:

* not invalidate the previously loaded file unless the new file is loaded successfully.
* upon a fatal error in the worker, clear the previously loaded file from the UI.

https://github.com/y-scope/yscope-log-viewer/commit/HEAD

### yscope-log-viewer version

https://github.com/y-scope/yscope-log-viewer/commit/1d5d95eab234190837c258efa9fef207621f8570

### Environment

* Browser: Firefox/Chrome
* OS: Windows

### Reproduction steps

* Drag and drop a file that can be successfully loaded into the log viewer.
* Drag and drop a file that can't be loaded into the log viewer.
* Observe the console error.
* Observe that page switching no longer works.

**Comment by kirkrodrigues** [comment]
Looking more into it, the worker is replaced immediately when trying to load a new file, so keeping the previous file loaded won't be possible without more significant code changes. At least, we should clear the UI's state when we fail to load another file.

**Comment by junhaoliao** [comment]
Fixed by #101
