### ISSUE TITLE
The "<=" in verbosity selection is confusing

### ISSUE THREAD

**Issue by diy1** [y-scope/yscope-log-viewer#8]
### Request

<img width="163" alt="image" src="https://user-images.githubusercontent.com/5174169/222457826-3e417a65-960b-4531-9277-210f9fa4709f.png">

The "<=" symbol in front of each verbosity level is confusing. First it took me a while to understand the meaning, and then I thought the opposite symbol, ">=", should be used (where I thought ERROR > INFO for example). 

### Possible implementation

Why don't we remove this symbol? Users understand the convention that a certain verbosity level is inclusive of all higher priority verbosity levels.

**Comment by vishalpalaniappan** [comment]
Hi diy1, 

Thanks for the enhancement request. The <= sign was initially added at the request of engineers who found it confusing without it. On further reflection and discussion with the team, a better way to display this would be to have a slider which shows which levels are included in the log. This would remove any ambiguity and likely be the best solution for new and experienced users. I will share a mockup for discussion before implementing the solution.

**Comment by diy1** [comment]
Got it.

**Comment by junhaoliao** [comment]
Fixed by #101
