### ISSUE TITLE
new-log-viewer: "dd" timestamp format specifier doesn't result in a zero-padded date.

### ISSUE THREAD

**Issue by kirkrodrigues** [y-scope/yscope-log-viewer#87]
### Bug

When the user specifies the timestamp format as `%d{yyyy-MM-dd HH:mm:ss.SSS}`, a timestamp like "2024-Oct-01 00:00:00.000" will get rendered as "2024-Oct-1 00:00:00.000", where the date is not zero-padded.

This appears to be a simple typo [here](https://github.com/y-scope/yscope-log-viewer/blob/main/new-log-viewer/src/services/formatters/LogbackFormatter.ts#L25) where we should be converting "dd" to "DD".

### yscope-log-viewer version

b6b63ea1a4fc76bed7a3882472ef0406ebc7f0f2

### Environment

Firefox 130.0.1.

### Reproduction steps

* Open a JSONL file that has a timestamp field with the format "2024-Oct-01 00:00:00.000" in the new log viewer.
* Observe that the rendered date is not zero-padded.

**Comment by junhaoliao** [comment]
This issue no longer exists since the introduction of the YScope formatter in #123 , right? Can we close this?
